# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc77e61de901a86b7b33227219df7a635f9810b3dcd6d534635601f3a8378204b175f23902b7a3cdb333e4994dfeb3a7383b063ef94a3241cad4cff74286ceb

test:
  secret_key_base: 495d94ac725ac8a7c2f922b193573837675061325031fa205a9f607b791f5bc6765283f89582c930c53cde28855f9c2ca07740a35777fc4613a42738d9a3eaea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
